spring:
  profiles:
    active: dev
app:
  jwt-secret: bXktbGVjdHVyZWZsb3ctMjAyNS1zZWN1cml0eS1rZXktc3ByaW5nLXN0cm9uZw==
  jwt-expiration-milliseconds: 86400000

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/lectureflow
    username: dldudwo
    password: 1118
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_batch_fetch_size: 1000
    open-in-view: false
    show-sql: true

---