# 워크플로우 이름: dev 브랜치 PR 시 빌드/테스트 자동 실행
name: CI - Pull Request to dev

# 실행 시마다 표시될 실행 제목
run-name: ${{ github.actor }} has opened a PR to dev

# 이 워크플로우는 dev 브랜치로의 PR 생성 시 실행됨
on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest  # GitHub에서 제공하는 Ubuntu 서버에서 실행

    defaults:
      run:
        working-directory: LectureFlow

    steps:
      # 레포지토리 코드 가져오기
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Java 17 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 빌드 수행
      - name: Build with Gradle
        run: ./gradlew build

      # 단위 테스트 실행
      - name: 테스트 실행
        run: ./gradlew test
